server:
  port: 9006
spring:
  application:
    name: hrm-pages
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hrm_pages
    username: root
    password: 123456
mybatis-plus:
  mapper-locations: classpath:com/liqiang/hrm/mapper/*Mapper.xml
  type-aliases-package: com.liqiang.hrm.domain,com.liqiang.hrm.query
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1024/eureka
  instance:
    prefer-ip-address: true
