server:
  port: 4399
spring:
  application:
    name: hrm-zuul-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1024/eureka
  instance:
    instance-id: gateway-4399.com
    prefer-ip-address: true
zuul:
  routes:
    system.serviceId: hrm-system #  需要被通过网关访问的服务的服务名
    system.path: /system/** # 把/system打头的所有请求都转发给hrm-system
  ignored-services: "*"
  prefix: /services
  retryable: true #是否重试


ribbon:
  ConnectTimeout: 250 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 2 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 3000 # 熔断超时时长：3000ms